---
title: "Trends in KEEN Kelp Data"
author: "Jarrett Byrnes"
date: "10/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
```

# What species are in the quad data?

```{r dat, echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)
library(readr)
library(purrr)
library(ggplot2)
library(lme4)
library(broom.mixed)
library(tidyr)

kelp <- read_csv("data/keen/keen_kelp.csv")

```


```{r, echo = FALSE}

tseries_plot <- function(adf){
  
  ggplot(adf,
         aes(y = WET_WEIGHT, x = YEAR,
             color = TRANSECT)) +
    stat_summary(fun.data = mean_se) +
    stat_summary(fun.data = mean_se, geom = "line") +
    facet_wrap(~SITE, nrow = 2) +
    labs(color = "Transect", 
         y = "Wet Weight per Individual",  x = "Year",
         title = paste(adf$SPECIES[1], "- ", adf$SP_CODE[1])) 
}


tseries_fun <- function(adf){
  lmer(WET_WEIGHT ~ YEAR * SITE + (1|TRANSECT),
               data = adf)
}

generate_output <- function(adf){
  cat(paste0("## ", adf$SPECIES[1], "  \n<br>"))
  
  tseries_plot(adf) %>% print()
  
  tseries_fun(adf) %>% 
    car::Anova(test.statistic  = "Chisq") %>% 
    tidy() %>%
    knitr::kable("html", digits = 3) %>% 
    kableExtra::kable_styling() %>%
    print
  
  cat("\n\n")
}
```


What are the trends in wet weight over time?
```{r, echo = TRUE, results = "asis", warning = FALSE}
kelp_complete <- kelp %>%
  filter(SP_CODE %in% c("SL", "AGCL", "LADI", ""))
walk(split(kelp_complete, kelp_complete$SP_CODE), generate_output)
```